export const dummyData = [
  {
    id: 1,
    name: "MacBook Pro 2021",
    price: "$999",
    originalPrice: "$1299",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop",
    tags: ["Electronics", "Laptop", "Apple"],
    description: "A used laptop in good condition, comes with charger.",
    brand: "Apple",
    condition: "Good",
    location: "San Francisco, CA",
    listedDate: "2024-02-15"
  },
  {
    id: 2,
    name: "Vintage Book Collection",
    price: "$150",
    originalPrice: "$200",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&h=400&fit=crop",
    tags: ["Books", "Vintage", "Collectibles"],
    description: "A curated collection of classic literature in excellent condition.",
    brand: "Various",
    condition: "Very Good",
    location: "Boston, MA",
    listedDate: "2024-02-10"
  },
  {
    id: 3,
    name: "PlayStation 5 Digital Edition",
    price: "$399",
    originalPrice: "$499",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&h=400&fit=crop",
    tags: ["Electronics", "Games", "Console"],
    description: "Like-new PS5 Digital Edition with two controllers.",
    brand: "Sony",
    condition: "Excellent",
    location: "Austin, TX",
    listedDate: "2024-02-17"
  },
  {
    id: 4,
    name: "Breville Barista Express",
    price: "$450",
    originalPrice: "$699",
    image: "https://images.unsplash.com/photo-1587080413959-06b859fb107d?w=600&h=400&fit=crop",
    tags: ["Home", "Appliance", "Coffee"],
    description: "Semi-automatic espresso machine, perfect for home baristas.",
    brand: "Breville",
    condition: "Like New",
    location: "Seattle, WA",
    listedDate: "2024-02-14"
  },
  {
    id: 6,
    name: "IKEA Desk",
    price: "$100",
    originalPrice: "$150",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&h=400&fit=crop",
    tags: ["Furniture", "Office", "Desk"],
    description: "A simple and functional desk for your study space.",
    brand: "IKEA",
    condition: "Good",
    location: "Los Angeles, CA",
    listedDate: "2024-02-12"
  },
  {
    id: 7,
    name: "Nike Air Max Sneakers",
    price: "$80",
    originalPrice: "$120",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=400&fit=crop",
    tags: ["Fashion", "Shoes", "Nike"],
    description: "Gently used Nike sneakers in great condition.",
    brand: "Nike",
    condition: "Very Good",
    location: "Chicago, IL",
    listedDate: "2024-02-13"
  },
  {
    id: 9,
    name: "Used Dorm Fridge",
    price: "$120",
    originalPrice: "$180",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&h=400&fit=crop",
    tags: ["Appliances", "Fridge", "Dorm"],
    description: "Compact fridge perfect for small spaces or dorm rooms.",
    brand: "Haier",
    condition: "Good",
    location: "Miami, FL",
    listedDate: "2024-02-18"
  },
  {
    id: 10,
    name: "Ergonomic Office Chair",
    price: "$120",
    originalPrice: "$200",
    image: "https://images.unsplash.com/photo-1589384267710-7a170981ca78?w=600&h=400&fit=crop",
    tags: ["Furniture", "Office", "Chair"],
    description: "Comfortable ergonomic chair for long study sessions.",
    brand: "Herman Miller",
    condition: "Very Good",
    location: "Seattle, WA",
    listedDate: "2024-02-14"
  }
];
